spring:
  application:
    name: kata-probe-navigation-service
  datasource:
    url: jdbc:h2:mem:probe_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update  # Options: create, update, validate, none
      show-sql: true  # Logs SQL queries for debugging
  h2:
    console:
      enabled: true
      path: /h2-console
